export const headingIconText = {
  // home page
  aboutUs__headingIconText: "About Us",
  services__headingIconText: "Services",
  yourDream__headingIconText: "You Dream It... We Create It",
  floorNow__headingIconText: "Floor Now, Pay Over Time",
  gallery__headingIconText: "Gallery",
  review__headingIconText: "Review",
  services__headingIconText: "Services Areas",
  contactNow__headingIconText: "Connect Now",

  // flooring installation page
  aboutUs__headingIconText: "About Us",
  installation__headingIconText: "#1 Installation",
  residentialAndCommercial__headingIconText: "Residential & Commercial",
  flooringInstallation__headingIconText: "Flooring Installation",
  bestFlooring__headingIconText: "Best Flooring",
  services__headingIconText: "Services",
  flooringContractors__headingIconText: "Flooring Contractors",
  workingProcess__headingIconText: "Working Process",
  gallery__headingIconText: "Gallery",
  review__headingIconText: "Review",
  trustUs__headingIconText: "Trust Us",
  whyChooseUs__headingIconText: "Why Choose Us",
  faq__headingIconText: "FAQ",
  servicesArea__headingIconText: "Services Area",
  startYourProject__headingIconText: "Start Your Project With Us",
  howWeDesign__headingIconText: "How We Design",
  costComparison__headingIconText: "Cost Comparison",

  // bathroom remodel page
  aboutUs__headingIconText: "About Us",
  contractors__headingIconText: "Contractors",
  experienced__headingIconText: "Experienced",
  equippedAdnExpert__headingIconText: "Equipped and Expert",
  elevatingDesign__headingIconText: "Elevating Design",
  benefits__headingIconText: "Benefits",
  gallery__headingIconText: "Gallery",
  streamlinedProcess__headingIconText: "Streamlined Process",
  servicesIncluded__headingIconText: "Services Included",
  review__headingIconText: "Review",
  cost__headingIconText: "Cost",
  considerationAndLimiting__headingIconText: "Consideration and Limiting",
  whyChoose__headingIconText: "Choose Us",
  bathroomInstallers__headingIconText: "Installers",
  faq__headingIconText: "FAQ",
  servicesArea__headingIconText: "Services Area",

  // Kitchen Remodel in Cypress page
  aboutUs__headingIconText: "About Us",
  experiencedAndWellEquipped__headingIconText: "Experienced & Well-Equipped",
  elevating__headingIconText: "Elevating",
  expertContractors__headingIconText: "Expert Contractors ",
  professional__headingIconText: "Professional",
  doesAndDoNot__headingIconText: "Do's & Don't",
  gallery__headingIconText: "Gallery",
  comprehensive__headingIconText: "Comprehensive",
  outdoorKitchen__headingIconText: "Outdoor Kitchen",
  innovative__headingIconText: "Innovative",
  cost__headingIconText: "Cost",
  review__headingIconText: "Review",
  whyChoose__headingIconText: "Why Choose",
  revitalize__headingIconText: "Revitalize",
  workWithUs__headingIconText: "Work with Us",
  freshNewLookWithUs__headingIconText: "Fresh New Look With Us",
  faq__headingIconText: "FAQ",
  servicesArea__headingIconText: "Services Area",
  servicesArea__headingIconText: "Services Area",

  // Vinyl Flooring In CypressTX page
  aboutUs__headingIconText: "About Us",
  installation__headingIconText: "#1 Installation",
  blendsStyleAndDurability__headingIconText: "Blends Style and Durability",
  whyItTheBestChoice__headingIconText: "Why It's the Best Choice",
  benefits__headingIconText: "Benefits",
  type__headingIconText: "Type",
  gallery__headingIconText: "Gallery",
  workingProcess__headingIconText: "Working Process",
  repair__headingIconText: "Repair",
  cleaner__headingIconText: "Cleaner",
  mistakes__headingIconText: "Mistakes",
  caring__headingIconText: "Caring",
  review__headingIconText: "Review",
  discover__headingIconText: "Discover",
  youCanTrust__headingIconText: "You Can Trust",
  faq__headingIconText: "FAQ",
  services__headingIconText: "Services",
  connectNow__headingIconText: "Connect Now",
  connectNow__headingIconText: "Connect Now",

  // Roofing Contractor in Cypress, TX page 
  aboutUs__headingIconText : "About Us",
  contractor__headingIconText : "#1 Contractor",
  wellEquipped__headingIconText : "Well Equipped",
  excellentDesign__headingIconText : "Excellent Design",
  workingProcess__headingIconText : "Working Process",
  gallery__headingIconText : "Gallery",
  bestRoofingService__headingIconText : "Best Roofing Service",
  solution__headingIconText : "Solution",
  review__headingIconText : "Review",
  nationwidRoofers__headingIconText : "Nationwide Roofers",
  whyChoose__headingIconText : "Why Choose",
  workWithUs__headingIconText : "Work with Us",
  faq__headingIconText : "FAQ",
  servicess__headingIconText : "Services",
  connectNow__headingIconText : "Connect Now",

  // Painting Contractors in Cypress, TX page 
  aboutUs__headingIconText : "About Us",
  premiumProducts__headingIconText : "Premium Products",
  paintingMaterials__headingIconText : "Painting Materials",
  process__headingIconText : "Process",
  painting__headingIconText : "Painting",
  gallery__headingIconText : "Gallery",
  paintingServices__headingIconText : "Painting Services",
  review__headingIconText : "Review",
  whyChoose__headingIconText : "Why Choose",
  expertPainters__headingIconText : "Expert Painters",
  youCanTrust__headingIconText : "You Can Trust",
  faq__headingIconText : "FAQ",
  services__headingIconText : "Services",
  connectNow__headingIconText : "Connect Now",


  
};
